import { lesson, module as mod, project, milestone } from "../build";

export const M1 = milestone({
  id: "01-foundations",
  number: 1,
  title: "AI Orientation, Digital Foundations & the Web",
  shortTitle: "Foundations",
  description:
    "Take a complete beginner from 'what even is a computer?' to a deployed, version-controlled personal web page, with one honest first AI experiment along the way.",
  entryState: "No programming, no command line, no Git, no AI experience.",
  exitCapability:
    "Learner can operate a professional workstation (terminal, editor, browser devtools), write and deploy a small HTML/CSS/JavaScript page under Git, and articulate what AI is, what it is not, and where it fits.",
  prerequisiteMilestones: [],
  competencyIds: ["LM-STUDY-001", "DF-WORK-001", "DF-WEB-001", "CT-DECOMP-001", "SE-VCS-001"],
  knowledgeDomains: ["META", "DIGI", "OS", "NET", "THINK", "RESP"],
  projects: [
    project("M1.P1", "Set up a professional workstation", "micro", 2),
    project("M1.P2", "First HTML page, hand-written", "micro", 2),
    project("M1.P3", "Styled personal landing page", "small", 6),
    project("M1.P4", "Version control with Git and GitHub", "micro", 3),
    project("M1.P5", "Interactive page with JavaScript", "small", 8),
    project("M1.P6", "Flagship: Deployed personal web presence", "medium", 15, true),
  ],
  flagshipProjectId: "M1.P6",
  gate:
    "Learner's personal site is live at a public URL, source is in a GitHub repository they can navigate, and they can explain the request/response path from browser to server.",
  estimatedHours: { min: 40, max: 60 },
  modules: [
    mod({
      id: "M1.M1",
      order: 1,
      title: "Orientation: what AI is, and how to learn it",
      purpose: "Give the learner an honest, motivating map of AI and of how they will learn it in this curriculum.",
      outcomes: [
        "Explain in plain language what modern AI systems are and are not.",
        "Distinguish rules-based, classical ML, and deep-learning approaches at an intuition level.",
        "Describe how they will learn: Learn → Visualize → Practice → Build → Reflect.",
      ],
      advancesProject: "M1.P1",
      deliverable: "A written learner charter: goals, weekly rhythm, and honest starting point, committed as `learner-charter.md` on their machine.",
      lessons: [
        lesson({
          id: "M1.M1.L1",
          title: "What AI is, and what it isn't",
          bigIdea: "AI is software that learns patterns from data or examples, not a mind and not magic.",
          whyItMatters: "Learners arrive with cartoon models of AI. A right-sized mental model prevents years of misunderstanding.",
          objectives: [
            "State three honest definitions of AI at different levels of precision.",
            "Give one everyday example each of rules-based automation, classical ML, and generative AI.",
          ],
          keyConcepts: ["input/output view of a system", "training vs inference", "rules vs learned patterns", "hype vs capability"],
          practice: "Sort ten short product descriptions into rules-based, classical ML, or generative AI, with a one-sentence justification for each.",
          buildStep: "Write the first paragraph of the learner charter: 'Why I want to learn AI, and what I currently believe it is.'",
          aiConnection: "This mental model is reused every time the learner evaluates a new AI product, paper, or claim.",
          competencyIds: ["LM-STUDY-001", "RAI-LIT-001"],
          knowledgeDomains: ["META", "LLM"],
          minutes: 45,
        }),
        lesson({
          id: "M1.M1.L2",
          title: "How this curriculum works",
          bigIdea: "Understanding is built by cycling through Learn, Visualize, Practice, Build, and Reflect — not by consuming content.",
          whyItMatters: "Adult beginners overestimate reading and underestimate retrieval and building. Naming the rhythm sets expectations.",
          objectives: [
            "Describe each of the five phases and what it produces.",
            "Plan a realistic weekly study cadence for their own life.",
          ],
          prerequisites: ["M1.M1.L1"],
          keyConcepts: ["retrieval practice", "spaced repetition", "deliberate practice", "authentic building"],
          practice: "Predict which of five study behaviours will produce the most durable learning, then reveal the answer with a short explanation.",
          buildStep: "Add a weekly rhythm section to the learner charter.",
          aiConnection: "The same feedback-loop thinking underlies model training: measurable objective, tight loop, honest evaluation.",
          competencyIds: ["LM-STUDY-001", "LM-PLAN-001"],
          knowledgeDomains: ["META"],
          minutes: 30,
        }),
        lesson({
          id: "M1.M1.L3",
          title: "Your first AI experiment",
          bigIdea: "You can already interact with a real AI system today; observing it is the first step to engineering it.",
          whyItMatters: "Ground the abstract in a concrete first interaction before spending weeks on prerequisites.",
          objectives: [
            "Send a prompt to a hosted LLM and read the response critically.",
            "Identify one thing the model got right and one it got wrong or uncertain.",
          ],
          prerequisites: ["M1.M1.L2"],
          keyConcepts: ["prompt", "response", "non-determinism", "confident-sounding wrongness"],
          practice: "Run three prompts (factual, creative, adversarial) and record the model's behaviour in a short table.",
          buildStep: "Save the transcript as `first-ai-experiment.md` in the workstation project.",
          aiConnection: "This is the exact interaction pattern the learner will later build, evaluate, and deploy at scale.",
          competencyIds: ["LLM-USE-001", "RAI-LIT-001"],
          knowledgeDomains: ["LLM", "META"],
          minutes: 45,
        }),
      ],
    }),
    mod({
      id: "M1.M2",
      order: 2,
      title: "Digital workstation",
      purpose: "Set up the tools every future lesson assumes: OS shell, editor, browser, and a sane home for projects.",
      outcomes: [
        "Navigate a filesystem from the terminal.",
        "Open, edit, and save files in a real editor with confidence.",
        "Explain the difference between an application, a process, and a file.",
      ],
      prerequisites: ["M1.M1"],
      advancesProject: "M1.P1",
      deliverable: "A working workstation with a `projects/` directory, a terminal cheat-sheet the learner wrote themselves, and the editor configured.",
      lessons: [
        lesson({
          id: "M1.M2.L1",
          title: "How a computer runs software",
          bigIdea: "A computer runs programs by moving bytes between disk, memory, and CPU under the control of an operating system.",
          whyItMatters: "Without this picture, every later error message reads like magic.",
          objectives: [
            "Sketch the disk / RAM / CPU / OS relationship.",
            "Explain in plain language what happens when you 'open an app'.",
          ],
          keyConcepts: ["OS", "process", "file", "memory vs storage"],
          practice: "Trace what happens, step by step, when the user double-clicks the browser icon.",
          buildStep: "Add a one-paragraph 'how my computer runs software' note to the workstation README.",
          aiConnection: "GPU vs CPU, model in memory vs on disk, and inference cost all sit on this foundation.",
          competencyIds: ["DF-WORK-001"],
          knowledgeDomains: ["SYS", "OS"],
          minutes: 40,
        }),
        lesson({
          id: "M1.M2.L2",
          title: "The terminal, honestly",
          bigIdea: "The shell is a text conversation with the computer; every command has a name, arguments, and an exit code.",
          whyItMatters: "The terminal is the single tool that follows the learner from lesson 1 to production AI systems.",
          objectives: [
            "Move around the filesystem with `cd`, `ls`, `pwd`.",
            "Create, move, and delete files safely.",
            "Read a command's help output.",
          ],
          prerequisites: ["M1.M2.L1"],
          keyConcepts: ["working directory", "path", "flag", "man/help"],
          practice: "Complete a short scavenger hunt: create a nested directory, move a file into it, and list contents recursively.",
          buildStep: "Set up the `projects/` directory structure that every future project will live inside.",
          aiConnection: "Every training run, deployment, and evaluation script will be launched from a terminal.",
          competencyIds: ["DF-WORK-001", "DF-CLI-001"],
          knowledgeDomains: ["OS"],
          minutes: 60,
        }),
        lesson({
          id: "M1.M2.L3",
          title: "Editor, browser, and devtools",
          bigIdea: "A code editor and the browser devtools are your microscopes; you cannot debug what you cannot see.",
          whyItMatters: "Fluency with these tools compounds over the entire curriculum.",
          objectives: [
            "Open a folder as a project in a real editor.",
            "Inspect an element and view the network tab in browser devtools.",
          ],
          prerequisites: ["M1.M2.L2"],
          keyConcepts: ["project folder", "syntax highlighting", "DOM inspector", "network tab"],
          practice: "Open any public webpage, identify one HTML element, and describe one network request the page made.",
          buildStep: "Configure the editor with a workspace pointed at `projects/`.",
          aiConnection: "The same devtools reveal exactly what an AI-powered web app sends to a model provider — a critical evaluation skill.",
          competencyIds: ["DF-WORK-001", "DF-WEB-001"],
          knowledgeDomains: ["DIGI", "NET"],
          minutes: 45,
        }),
      ],
    }),
    mod({
      id: "M1.M3",
      order: 3,
      title: "How the web works",
      purpose: "Give the learner a concrete, request-level mental model of the web so deployment stops feeling like magic.",
      outcomes: [
        "Trace a URL from typed address to rendered page.",
        "Distinguish client, server, DNS, and HTTP at the level required to deploy a site.",
      ],
      prerequisites: ["M1.M2"],
      advancesProject: "M1.P2",
      deliverable: "A hand-drawn (or ASCII) diagram of a request/response cycle, committed with the personal page.",
      lessons: [
        lesson({
          id: "M1.M3.L1",
          title: "URLs, DNS, and HTTP in plain language",
          bigIdea: "The web is a giant request/response system: clients ask, servers answer, and DNS turns names into addresses.",
          whyItMatters: "Every AI product the learner will build later is exposed through the same request/response layer.",
          objectives: [
            "Break a URL into scheme, host, path, and query.",
            "Describe DNS as a phonebook and HTTP as a letter format.",
          ],
          keyConcepts: ["URL", "DNS", "HTTP method", "status code"],
          practice: "Given five status codes, predict what the user saw for each and check with a live example.",
          buildStep: "Add a labelled diagram of the request path to the workstation README.",
          aiConnection: "Every hosted model API is an HTTP endpoint the learner will call, secure, and monitor.",
          competencyIds: ["DF-WEB-001"],
          knowledgeDomains: ["NET"],
          minutes: 45,
        }),
        lesson({
          id: "M1.M3.L2",
          title: "HTML: the structure of a page",
          bigIdea: "HTML gives meaning to text; the browser turns that structure into a document tree.",
          whyItMatters: "Structure precedes style, and semantics is what makes pages accessible and machine-readable.",
          objectives: [
            "Author a valid HTML document from scratch.",
            "Use headings, lists, links, and images semantically.",
          ],
          prerequisites: ["M1.M3.L1"],
          keyConcepts: ["element", "attribute", "semantic tag", "document tree"],
          practice: "Given a plain-text bio, mark it up with the right semantic elements — no divs allowed.",
          buildStep: "Write `index.html` for the personal landing page.",
          aiConnection: "LLM-generated pages are only useful when a human can read, audit, and correct the HTML they produce.",
          competencyIds: ["DF-WEB-001"],
          knowledgeDomains: ["NET"],
          minutes: 60,
        }),
        lesson({
          id: "M1.M3.L3",
          title: "CSS just enough to be dangerous",
          bigIdea: "CSS is a rule system that decorates the document tree; you can go far with a small, principled subset.",
          whyItMatters: "We are not building a design career here — we need enough CSS to ship believable products.",
          objectives: [
            "Use selectors, the box model, and flexbox to lay out a page.",
            "Prefer semantic tokens over arbitrary values.",
          ],
          prerequisites: ["M1.M3.L2"],
          keyConcepts: ["selector", "box model", "flexbox", "custom properties"],
          practice: "Refactor an ugly page using at most 30 lines of CSS.",
          buildStep: "Style the personal landing page.",
          aiConnection: "AI product demos live or die on the last 5% of visual polish; enough CSS to ship is enough CSS to demo.",
          competencyIds: ["DF-WEB-001"],
          knowledgeDomains: ["NET"],
          minutes: 60,
        }),
        lesson({
          id: "M1.M3.L4",
          title: "A pinch of JavaScript",
          bigIdea: "JavaScript is the browser's built-in scripting language; a little of it turns a static page into an interactive one.",
          whyItMatters: "Interactive demos are the shortest path from an AI idea to something a user can try.",
          objectives: [
            "Attach a click handler that changes the DOM.",
            "Read an input value and update the page in response.",
          ],
          prerequisites: ["M1.M3.L3"],
          keyConcepts: ["event", "DOM update", "variable", "function"],
          practice: "Predict, then verify, what happens when a handler modifies an element mid-event.",
          buildStep: "Add one small interaction (e.g. a theme toggle) to the personal page.",
          aiConnection: "The same handler pattern powers a chat UI's Send button.",
          competencyIds: ["DF-WEB-001", "PY-PROG-001"],
          knowledgeDomains: ["NET", "PY"],
          minutes: 60,
        }),
      ],
    }),
    mod({
      id: "M1.M4",
      order: 4,
      title: "Version control with Git",
      purpose: "Introduce Git early so every subsequent project is version-controlled by default.",
      outcomes: [
        "Initialise a repository, stage, commit, and push to GitHub.",
        "Read a diff and recover from common mistakes.",
      ],
      prerequisites: ["M1.M3"],
      advancesProject: "M1.P4",
      deliverable: "The personal page pushed to a public GitHub repository with a meaningful commit history.",
      lessons: [
        lesson({
          id: "M1.M4.L1",
          title: "Why version control exists",
          bigIdea: "A repository is a time machine for your code, with named checkpoints and shareable history.",
          whyItMatters: "Learners who skip Git accumulate irrecoverable states; learners who adopt it early build professional habits.",
          objectives: [
            "Explain commits, branches, and remotes at an intuition level.",
            "Predict what `git status` will report in a given scenario.",
          ],
          keyConcepts: ["commit", "working tree", "staging area", "remote"],
          practice: "Given a sequence of file changes, predict the output of `git status` at each step.",
          buildStep: "Initialise the repo for the personal page and make the first commit.",
          aiConnection: "Reproducible AI experiments are impossible without versioned code and data.",
          competencyIds: ["SE-VCS-001"],
          knowledgeDomains: ["SWE"],
          minutes: 45,
        }),
        lesson({
          id: "M1.M4.L2",
          title: "Everyday Git workflow",
          bigIdea: "The daily workflow is small: edit, stage, commit, push — with a habit of writing why, not what.",
          whyItMatters: "A good habit here saves weeks of pain later.",
          objectives: [
            "Perform edit / stage / commit / push confidently.",
            "Write commit messages that explain intent.",
          ],
          prerequisites: ["M1.M4.L1"],
          keyConcepts: ["staging", "commit message", "push", "diff"],
          practice: "Rewrite three bad commit messages into ones that would help a future collaborator.",
          buildStep: "Push the personal page to a new GitHub repo.",
          aiConnection: "Every serious AI codebase is reviewed via pull requests built on this exact workflow.",
          competencyIds: ["SE-VCS-001", "COM-WRITE-001"],
          knowledgeDomains: ["SWE"],
          minutes: 60,
        }),
        lesson({
          id: "M1.M4.L3",
          title: "Recovering from mistakes",
          bigIdea: "Most Git 'disasters' are recoverable; the first move is always to read the state, not to panic.",
          whyItMatters: "Confidence to experiment comes from knowing you can undo.",
          objectives: [
            "Undo an unstaged edit, a staged edit, and a committed change.",
            "Read `git log` and `git reflog` at a survival level.",
          ],
          prerequisites: ["M1.M4.L2"],
          keyConcepts: ["checkout", "reset", "reflog", "detached HEAD (survival level)"],
          practice: "Given a broken repo state, choose the safest recovery command from three options and justify it.",
          buildStep: "Deliberately break the repo, then restore it.",
          aiConnection: "Rolling back a bad model deploy is philosophically the same operation.",
          competencyIds: ["SE-VCS-001"],
          knowledgeDomains: ["SWE"],
          minutes: 45,
        }),
      ],
    }),
    mod({
      id: "M1.M5",
      order: 5,
      title: "Ship it: deployment and reflection",
      purpose: "Close the loop: deploy the site publicly, and reflect on what a 'shipped' artifact means.",
      outcomes: [
        "Deploy a static site to a public URL from GitHub.",
        "Explain the difference between local, staged, and deployed states.",
      ],
      prerequisites: ["M1.M4"],
      advancesProject: "M1.P6",
      deliverable: "Personal site deployed at a public URL, with a README describing what it is and how to run it locally.",
      lessons: [
        lesson({
          id: "M1.M5.L1",
          title: "From local to the internet",
          bigIdea: "Deployment is copying your built files to a computer with a public address and pointing a name at it.",
          whyItMatters: "Nothing exists until it is shippable and shipped.",
          objectives: [
            "Deploy the personal page via a static host connected to GitHub.",
            "Explain, in one paragraph, what happens between `git push` and the site being live.",
          ],
          keyConcepts: ["static hosting", "build vs deploy", "custom domain (mention only)"],
          practice: "Predict which of three changes will and will not appear on the live site without a redeploy, then verify.",
          buildStep: "Deploy the personal site.",
          aiConnection: "Every AI product this curriculum builds will follow the same 'push to deploy' rhythm.",
          competencyIds: ["DF-WEB-001", "SYS-DEPLOY-001"],
          knowledgeDomains: ["NET", "MLOPS"],
          minutes: 45,
        }),
        lesson({
          id: "M1.M5.L2",
          title: "Reading your own site like a stranger",
          bigIdea: "A shipped artifact is judged by users who never see the code — accessibility and clarity are features.",
          whyItMatters: "Every AI product will be judged the same way.",
          objectives: [
            "Audit the site with a keyboard and a screen-reader outline.",
            "List three concrete improvements and act on one.",
          ],
          prerequisites: ["M1.M5.L1"],
          keyConcepts: ["accessibility basics", "semantic markup", "contrast", "user empathy"],
          practice: "Navigate the deployed site using only the keyboard and record every friction point.",
          buildStep: "Fix the highest-impact accessibility issue and redeploy.",
          aiConnection: "Responsible AI starts with responsible product basics; you cannot bolt accessibility on later.",
          competencyIds: ["PROD-USER-001", "RAI-LIT-001"],
          knowledgeDomains: ["NET", "RESP"],
          minutes: 45,
        }),
        lesson({
          id: "M1.M5.L3",
          title: "Milestone 1 retrospective",
          bigIdea: "Learning consolidates through structured reflection, not through moving on.",
          whyItMatters: "A short honest retro is worth more than a longer next lesson.",
          objectives: [
            "Name three things they now understand that they did not at Day 1.",
            "Name one topic they know they don't yet understand.",
          ],
          prerequisites: ["M1.M5.L2"],
          keyConcepts: ["retrieval-based review", "known unknowns"],
          practice: "Answer ten short recall questions covering the milestone, without notes.",
          buildStep: "Publish a short 'What I built' post on the deployed site.",
          aiConnection: "Model cards and case studies are the same reflection ritual, applied to AI systems.",
          competencyIds: ["LM-STUDY-001", "COM-WRITE-001"],
          knowledgeDomains: ["META", "RESP"],
          minutes: 30,
        }),
      ],
    }),
  ],
});
