import { lesson, module as mod, project, milestone } from "../build";

export const M2 = milestone({
  id: "02-python-foundations",
  number: 2,
  title: "Programming Foundations with Python",
  shortTitle: "Python Foundations",
  description:
    "Turn the learner from a website author into a programmer. Python becomes the language they think and build in.",
  entryState: "Can operate a workstation, ship a static site, and use Git. No programming experience.",
  exitCapability:
    "Learner can decompose a problem, write correct Python programs of ~200 lines, work with files and APIs, and produce a small command-line toolkit.",
  prerequisiteMilestones: ["01-foundations"],
  competencyIds: ["CT-DECOMP-001", "PY-PROG-001", "PY-IO-001", "SE-VCS-001", "CT-CORR-001"],
  knowledgeDomains: ["THINK", "PY", "SWE"],
  projects: [
    project("M2.P1", "Python REPL warm-up", "micro", 2),
    project("M2.P2", "Text file processor", "small", 6),
    project("M2.P3", "API-consuming script", "small", 8),
    project("M2.P4", "Interactive TUI utility", "medium", 12),
    project("M2.P5", "Flagship: `cliops` toolkit", "medium", 20, true),
  ],
  flagshipProjectId: "M2.P5",
  gate: "Learner has published the `cliops` CLI toolkit to GitHub with a working README, at least three real subcommands, and honest error handling.",
  estimatedHours: { min: 60, max: 90 },
  modules: [
    mod({
      id: "M2.M1",
      order: 1,
      title: "Thinking like a programmer",
      purpose: "Give the learner a decomposition and correctness habit before syntax.",
      outcomes: [
        "Decompose a small task into inputs, steps, and outputs.",
        "State a program's correctness in one sentence before writing it.",
      ],
      advancesProject: "M2.P1",
      deliverable: "A written I/O contract for three small tasks.",
      lessons: [
        lesson({
          id: "M2.M1.L1",
          title: "Inputs, steps, outputs",
          bigIdea: "Every program is a function from inputs to outputs; naming those three is half the work.",
          whyItMatters: "Beginners jump to code and pay for it in bugs. Naming the shape saves hours.",
          objectives: ["Write an I/O contract for a small task.", "Identify the invariant a program must preserve."],
          keyConcepts: ["input", "output", "invariant", "example-driven design"],
          practice: "Given three informal tasks, write their I/O contracts.",
          buildStep: "Draft I/O contracts for the three subcommands `cliops` will eventually offer.",
          aiConnection: "ML models are also functions from inputs to outputs; contract thinking transfers directly.",
          competencyIds: ["CT-DECOMP-001", "CT-CORR-001"],
          knowledgeDomains: ["THINK"],
          minutes: 45,
        }),
        lesson({
          id: "M2.M1.L2",
          title: "The Python REPL as a lab",
          bigIdea: "The REPL is a scientific instrument: form a hypothesis, run one line, observe.",
          whyItMatters: "The REPL habit produces fast, honest feedback loops.",
          objectives: ["Evaluate expressions in the REPL.", "Predict values before pressing enter."],
          prerequisites: ["M2.M1.L1"],
          keyConcepts: ["expression vs statement", "value", "type"],
          practice: "Predict the value of 12 expressions before running them.",
          buildStep: "Complete the REPL warm-up (M2.P1).",
          aiConnection: "Notebook-driven ML is REPL-driven programming, made persistent.",
          competencyIds: ["PY-PROG-001"],
          knowledgeDomains: ["PY"],
          minutes: 45,
        }),
      ],
    }),
    mod({
      id: "M2.M2",
      order: 2,
      title: "Values, variables, control flow",
      purpose: "Introduce the smallest useful subset of Python for real programs.",
      outcomes: ["Use variables, conditionals, and loops correctly.", "Read Python errors and act on them."],
      prerequisites: ["M2.M1"],
      advancesProject: "M2.P2",
      deliverable: "A working text file processor script.",
      lessons: [
        lesson({
          id: "M2.M2.L1",
          title: "Values and types",
          bigIdea: "Every value has a type, and Python's errors mostly come from type surprises.",
          whyItMatters: "Type-mismatch bugs dominate the first hundred hours of a programmer's life.",
          objectives: ["Name the everyday types.", "Convert between them safely."],
          keyConcepts: ["int", "float", "str", "bool", "None", "type coercion"],
          practice: "Debug five snippets whose only problem is a type mismatch.",
          buildStep: "Parse a config value into the right type in the `cliops` scaffold.",
          aiConnection: "Tensors are typed arrays; type discipline scales up to ML with almost no changes.",
          competencyIds: ["PY-PROG-001"],
          knowledgeDomains: ["PY"],
          minutes: 45,
        }),
        lesson({
          id: "M2.M2.L2",
          title: "Conditionals and loops",
          bigIdea: "Programs get power from branching and repetition, not from magic.",
          whyItMatters: "Two constructs, done well, unlock 80% of small programs.",
          objectives: ["Write branching logic with `if`/`elif`/`else`.", "Iterate with `for` and `while` without off-by-one bugs."],
          prerequisites: ["M2.M2.L1"],
          keyConcepts: ["truthiness", "range", "iteration"],
          practice: "Trace by hand the output of three tricky loops before running them.",
          buildStep: "Iterate over the lines of a text file in the processor script.",
          aiConnection: "Training loops are — literally — loops. This habit transfers.",
          competencyIds: ["PY-PROG-001", "CT-CORR-001"],
          knowledgeDomains: ["PY", "THINK"],
          minutes: 60,
        }),
        lesson({
          id: "M2.M2.L3",
          title: "Reading errors",
          bigIdea: "A traceback is a map; the deepest frame you wrote is usually where you must look.",
          whyItMatters: "Beginners avoid errors; professionals read them.",
          objectives: ["Interpret common Python exceptions.", "Fix a bug by reading the traceback first."],
          prerequisites: ["M2.M2.L2"],
          keyConcepts: ["traceback", "exception type", "frame"],
          practice: "Given five tracebacks, locate the offending line before opening the source.",
          buildStep: "Add one honest error message to the text file processor.",
          aiConnection: "PyTorch stack traces follow the same rules.",
          competencyIds: ["PY-PROG-001", "SE-DEBUG-001"],
          knowledgeDomains: ["PY", "SWE"],
          minutes: 40,
        }),
      ],
    }),
    mod({
      id: "M2.M3",
      order: 3,
      title: "Data structures and functions",
      purpose: "Introduce the collection types and functions that structure real programs.",
      outcomes: ["Choose between list, dict, set, and tuple for a task.", "Write small, well-named functions."],
      prerequisites: ["M2.M2"],
      advancesProject: "M2.P2",
      deliverable: "Text file processor refactored into small named functions.",
      lessons: [
        lesson({
          id: "M2.M3.L1",
          title: "Lists, dicts, sets, tuples",
          bigIdea: "Choose the collection whose shape matches your data.",
          whyItMatters: "Wrong-shape collections force wrong-shape code.",
          objectives: ["Pick the right collection for four scenarios.", "Iterate over each idiomatically."],
          keyConcepts: ["list", "dict", "set", "tuple", "mutability"],
          practice: "Rewrite three snippets to use a more appropriate collection type.",
          buildStep: "Store word counts in a dict inside the processor.",
          aiConnection: "Feature engineering is largely picking the right data structure for the data.",
          competencyIds: ["PY-PROG-001", "CT-REP-001"],
          knowledgeDomains: ["PY", "THINK"],
          minutes: 60,
        }),
        lesson({
          id: "M2.M3.L2",
          title: "Functions and naming",
          bigIdea: "A function is a named idea; a good name is documentation.",
          whyItMatters: "Naming is the cheapest force multiplier in software.",
          objectives: ["Extract repeated code into a function.", "Write a short docstring."],
          prerequisites: ["M2.M3.L1"],
          keyConcepts: ["parameter", "return", "scope", "docstring"],
          practice: "Refactor a 40-line script into named functions and re-run its tests.",
          buildStep: "Refactor the text file processor into functions.",
          aiConnection: "Well-named preprocessing functions are the difference between a legible and a haunted ML pipeline.",
          competencyIds: ["PY-PROG-001", "SE-CODE-001"],
          knowledgeDomains: ["PY", "SWE"],
          minutes: 60,
        }),
      ],
    }),
    mod({
      id: "M2.M4",
      order: 4,
      title: "Files, the world outside, and the CLI",
      purpose: "Move Python from toy scripts to programs that read the world and answer back.",
      outcomes: [
        "Read and write files safely.",
        "Call an HTTP API and handle failure.",
        "Structure a small program as a real CLI.",
      ],
      prerequisites: ["M2.M3"],
      advancesProject: "M2.P5",
      deliverable: "`cliops` toolkit v0: multi-subcommand CLI installed and runnable from the terminal.",
      lessons: [
        lesson({
          id: "M2.M4.L1",
          title: "Reading and writing files",
          bigIdea: "Files are one of the two doors between your program and the outside world.",
          whyItMatters: "Nearly all real programs live on files.",
          objectives: ["Use `with open(...)` correctly.", "Handle missing or malformed input honestly."],
          keyConcepts: ["file handle", "encoding", "path", "context manager"],
          practice: "Given a file that is 'usually well-formed', find the three edge cases that would crash a naive script.",
          buildStep: "Add a `cliops words` subcommand that reads a file and reports statistics.",
          aiConnection: "Every dataset starts as files on disk.",
          competencyIds: ["PY-IO-001"],
          knowledgeDomains: ["PY"],
          minutes: 60,
        }),
        lesson({
          id: "M2.M4.L2",
          title: "Calling an HTTP API",
          bigIdea: "An HTTP client turns a URL into data, with rules and failure modes you must respect.",
          whyItMatters: "Every hosted AI model is behind an HTTP API.",
          objectives: ["Make a GET request and parse JSON.", "Handle a non-2xx response."],
          prerequisites: ["M2.M4.L1"],
          keyConcepts: ["requests library", "JSON", "status code", "timeout"],
          practice: "Predict what an API returns for three deliberately malformed queries, then verify.",
          buildStep: "Add a `cliops fetch` subcommand that hits a public API.",
          aiConnection: "This is the same code path as calling an LLM provider.",
          competencyIds: ["PY-IO-001", "DF-WEB-001"],
          knowledgeDomains: ["PY", "NET"],
          minutes: 60,
        }),
        lesson({
          id: "M2.M4.L3",
          title: "Command-line interfaces that don't lie",
          bigIdea: "A CLI is a promise: subcommand names, arguments, exit codes, and helpful `--help`.",
          whyItMatters: "The learner's first serious tool goes here; habits set today persist.",
          objectives: ["Design a subcommand structure.", "Produce useful `--help` output."],
          prerequisites: ["M2.M4.L2"],
          keyConcepts: ["argparse", "exit code", "stdout vs stderr"],
          practice: "Critique a real CLI's `--help` and propose two concrete improvements.",
          buildStep: "Assemble `cliops` v0.1 with `words`, `fetch`, and a third subcommand of the learner's choice.",
          aiConnection: "Model training scripts are CLIs; good CLI hygiene compounds in ML.",
          competencyIds: ["PY-IO-001", "SE-CLI-001"],
          knowledgeDomains: ["PY", "SWE"],
          minutes: 75,
        }),
      ],
    }),
  ],
});
