import { lesson, module as mod, project, milestone } from "../build";

export const M3 = milestone({
  id: "03-professional-python",
  number: 3,
  title: "Professional Python & Software Craft",
  shortTitle: "Software Craft",
  description:
    "Turn `cliops` into professional software: tested, typed, linted, packaged, and continuously integrated.",
  entryState: "Learner ships small Python scripts and a working CLI toolkit.",
  exitCapability:
    "Learner produces Python packages with a passing test suite, static type checks, linters, formatted code, and a CI pipeline on every push.",
  prerequisiteMilestones: ["02-python-foundations"],
  competencyIds: ["SE-TEST-001", "SE-TYPE-001", "SE-CI-001", "SE-PKG-001", "COM-WRITE-001"],
  knowledgeDomains: ["PY", "SWE"],
  projects: [
    project("M3.P1", "Add a test suite to `cliops`", "small", 6),
    project("M3.P2", "Typed refactor", "small", 6),
    project("M3.P3", "Lint, format, pre-commit", "micro", 3),
    project("M3.P4", "Packaging & publish", "small", 8),
    project("M3.P5", "Flagship: CI/CD pipeline", "medium", 15, true),
  ],
  flagshipProjectId: "M3.P5",
  gate: "`cliops` is a published package with CI running tests, type-checks, and linters on every push; badges are green.",
  estimatedHours: { min: 40, max: 60 },
  modules: [
    mod({
      id: "M3.M1",
      order: 1,
      title: "Testing as a design tool",
      purpose: "Introduce tests as the primary feedback loop for code correctness.",
      outcomes: ["Write unit tests with pytest.", "Distinguish tests that catch bugs from tests that lock behaviour."],
      advancesProject: "M3.P1",
      deliverable: "Passing pytest suite for `cliops` with meaningful coverage of the happy path and two edge cases.",
      lessons: [
        lesson({
          id: "M3.M1.L1",
          title: "Why tests exist",
          bigIdea: "A test is an executable claim about your code's behaviour.",
          whyItMatters: "Untested code is a rumour; tested code is a contract.",
          objectives: ["Explain the value of a test suite to a non-programmer.", "Identify what to test first in a small program."],
          keyConcepts: ["unit test", "assertion", "regression"],
          practice: "Given a small function, list three assertions worth writing and one that would be a waste.",
          buildStep: "Add the first three tests for `cliops words`.",
          aiConnection: "Every ML evaluation is a test suite in disguise.",
          competencyIds: ["SE-TEST-001", "CT-CORR-001"],
          knowledgeDomains: ["SWE"],
          minutes: 45,
        }),
        lesson({
          id: "M3.M1.L2",
          title: "pytest fluency",
          bigIdea: "pytest rewards clear naming and small fixtures.",
          whyItMatters: "The tool is small; the habits are what matter.",
          objectives: ["Write a fixture.", "Parametrise a test."],
          prerequisites: ["M3.M1.L1"],
          keyConcepts: ["fixture", "parametrize", "assert"],
          practice: "Convert three copy-pasted tests into a single parametrised test.",
          buildStep: "Parametrise the tests for `cliops words`.",
          aiConnection: "The same parametrisation pattern powers evaluation grids in ML.",
          competencyIds: ["SE-TEST-001"],
          knowledgeDomains: ["SWE"],
          minutes: 45,
        }),
      ],
    }),
    mod({
      id: "M3.M2",
      order: 2,
      title: "Types, linters, and formatters",
      purpose: "Make invisible bugs visible with tooling.",
      outcomes: ["Annotate a codebase with types.", "Run and act on linter and formatter output."],
      prerequisites: ["M3.M1"],
      advancesProject: "M3.P2",
      deliverable: "`cliops` passes a strict type-check and a linter with no ignored errors.",
      lessons: [
        lesson({
          id: "M3.M2.L1",
          title: "Type annotations that pay for themselves",
          bigIdea: "Types are cheap documentation the machine reads.",
          whyItMatters: "Annotated code is easier to change; unannotated code is easier to break.",
          objectives: ["Annotate function signatures.", "Read a type-check error."],
          keyConcepts: ["typing", "Optional", "list[T]", "type-checker"],
          practice: "Given an untyped module, add the annotations a type-checker asks for.",
          buildStep: "Annotate `cliops` and fix the first ten type errors.",
          aiConnection: "Tensor shape mismatches are the ML analogue; type discipline transfers.",
          competencyIds: ["SE-TYPE-001"],
          knowledgeDomains: ["PY", "SWE"],
          minutes: 60,
        }),
        lesson({
          id: "M3.M2.L2",
          title: "Formatters and linters",
          bigIdea: "Automating style ends the debate.",
          whyItMatters: "Time saved bikeshedding is time available for learning.",
          objectives: ["Configure a formatter.", "Adopt a linter with a small, opinionated ruleset."],
          prerequisites: ["M3.M2.L1"],
          keyConcepts: ["formatter", "linter", "pre-commit"],
          practice: "Reject three linter warnings with justification and fix the rest.",
          buildStep: "Add a `pre-commit` config to `cliops`.",
          aiConnection: "Reproducible ML repos are always linted and formatted.",
          competencyIds: ["SE-CODE-001", "SE-CI-001"],
          knowledgeDomains: ["SWE"],
          minutes: 45,
        }),
      ],
    }),
    mod({
      id: "M3.M3",
      order: 3,
      title: "Packaging and publishing",
      purpose: "Ship code as a package other people (including future-you) can install.",
      outcomes: ["Structure a Python package.", "Publish it to a package index (real or test)."],
      prerequisites: ["M3.M2"],
      advancesProject: "M3.P4",
      deliverable: "`cliops` installable via `pipx` or equivalent from a package index.",
      lessons: [
        lesson({
          id: "M3.M3.L1",
          title: "Anatomy of a Python package",
          bigIdea: "A package is a project layout plus a manifest.",
          whyItMatters: "Every serious tool the learner will use is a package.",
          objectives: ["Explain a src-layout project.", "Author a `pyproject.toml`."],
          keyConcepts: ["package", "module", "pyproject.toml", "entry point"],
          practice: "Given a broken package layout, identify the two problems.",
          buildStep: "Restructure `cliops` as a src-layout package.",
          aiConnection: "ML libraries follow the same conventions; reading them becomes easier.",
          competencyIds: ["SE-PKG-001"],
          knowledgeDomains: ["PY", "SWE"],
          minutes: 60,
        }),
        lesson({
          id: "M3.M3.L2",
          title: "Semantic versioning and changelogs",
          bigIdea: "Version numbers are a promise; changelogs are how you keep it.",
          whyItMatters: "Users of your code (including your future self) rely on both.",
          objectives: ["Pick a next version for three change scenarios.", "Draft a `CHANGELOG.md` entry."],
          prerequisites: ["M3.M3.L1"],
          keyConcepts: ["semver", "changelog", "breaking change"],
          practice: "Classify five code changes as patch, minor, or major.",
          buildStep: "Cut version 0.1.0 of `cliops` with a changelog.",
          aiConnection: "Model versioning follows analogous discipline in MLOps.",
          competencyIds: ["SE-PKG-001", "COM-WRITE-001"],
          knowledgeDomains: ["SWE"],
          minutes: 45,
        }),
      ],
    }),
    mod({
      id: "M3.M4",
      order: 4,
      title: "Continuous integration",
      purpose: "Make quality gates automatic.",
      outcomes: ["Author a CI workflow.", "Interpret a red build."],
      prerequisites: ["M3.M3"],
      advancesProject: "M3.P5",
      deliverable: "CI pipeline that runs tests, type-checks, and linters on every push and pull request.",
      lessons: [
        lesson({
          id: "M3.M4.L1",
          title: "What CI is really doing",
          bigIdea: "CI is a robot that runs your quality gates on someone else's computer, on every change.",
          whyItMatters: "Local-only quality gates are optional; CI-enforced ones are not.",
          objectives: ["Read a CI workflow file.", "Explain what a green build proves and what it does not."],
          keyConcepts: ["workflow", "job", "step", "cache"],
          practice: "Given a red build log, identify which gate failed and why.",
          buildStep: "Add a CI workflow to `cliops`.",
          aiConnection: "ML CI adds evaluation and model regression checks on top of the same primitives.",
          competencyIds: ["SE-CI-001"],
          knowledgeDomains: ["SWE"],
          minutes: 60,
        }),
        lesson({
          id: "M3.M4.L2",
          title: "Continuous delivery, honestly",
          bigIdea: "CD is CI plus a deploy step, gated on quality signals.",
          whyItMatters: "Understanding the split prevents cargo-culting later.",
          objectives: ["Extend CI to publish on tag.", "Describe rollback strategy in one paragraph."],
          prerequisites: ["M3.M4.L1"],
          keyConcepts: ["CD", "release tag", "artifact"],
          practice: "Predict what a tag push will do given a given workflow file.",
          buildStep: "Publish `cliops` 0.1.0 automatically on tag push.",
          aiConnection: "Model release pipelines use the same primitives.",
          competencyIds: ["SE-CI-001", "SYS-DEPLOY-001"],
          knowledgeDomains: ["SWE", "MLOPS"],
          minutes: 60,
        }),
      ],
    }),
  ],
});
