import { lesson, module as mod, project, milestone } from "../build";

export const M4 = milestone({
  id: "04-data-fluency",
  number: 4,
  title: "Data Fluency: Wrangling, SQL & Visualization",
  shortTitle: "Data Fluency",
  description: "Learn to acquire, model, clean, transform, query, and visualize data as the raw material of AI.",
  entryState: "Learner ships professional Python packages with CI.",
  exitCapability:
    "Learner can load a messy real-world dataset, model it relationally, transform it with pandas, query it with SQL, visualize it honestly, and publish a small data product.",
  prerequisiteMilestones: ["03-professional-python"],
  competencyIds: ["DA-INGEST-001", "DA-CLEAN-001", "DA-SQL-001", "DA-VIZ-001", "COM-WRITE-001"],
  knowledgeDomains: ["DATA", "PY", "RESP"],
  projects: [
    project("M4.P1", "Notebook-first data exploration", "small", 6),
    project("M4.P2", "Pandas transformation pipeline", "small", 10),
    project("M4.P3", "Relational modelling & SQL", "medium", 12),
    project("M4.P4", "Visualisation & narrative", "small", 8),
    project("M4.P5", "Flagship: Public data product", "medium", 25, true),
  ],
  flagshipProjectId: "M4.P5",
  gate: "A deployed data product on a real dataset with reproducible pipeline, visualizations, and a written narrative.",
  estimatedHours: { min: 60, max: 90 },
  modules: [
    mod({
      id: "M4.M1",
      order: 1,
      title: "Data at rest",
      purpose: "Meet data as it actually arrives in the wild.",
      outcomes: ["Load CSV, JSON, and API data into memory.", "Describe a dataset honestly."],
      advancesProject: "M4.P1",
      deliverable: "Exploration notebook with a written honest description of a real dataset.",
      lessons: [
        lesson({
          id: "M4.M1.L1",
          title: "Tabular data mental model",
          bigIdea: "Most useful data has rows (observations) and columns (features).",
          whyItMatters: "This picture is the substrate of classical ML.",
          objectives: ["Load a CSV.", "Report shape, dtypes, and missing values."],
          keyConcepts: ["row", "column", "dtype", "missingness"],
          practice: "Given a CSV of unknown structure, describe it in five sentences.",
          buildStep: "Load the flagship dataset into a notebook.",
          aiConnection: "Feature matrices are tabular data with intent.",
          competencyIds: ["DA-INGEST-001"],
          knowledgeDomains: ["DATA"],
          minutes: 45,
        }),
        lesson({
          id: "M4.M1.L2",
          title: "Notebooks without regret",
          bigIdea: "Notebooks are for exploration; production code lives elsewhere.",
          whyItMatters: "Notebook abuse is the #1 source of unreproducible ML.",
          objectives: ["Structure a notebook top-to-bottom runnable.", "Extract a reusable function."],
          prerequisites: ["M4.M1.L1"],
          keyConcepts: ["kernel", "cell order", "extract-to-module"],
          practice: "Take a hairy notebook and identify the three functions to extract.",
          buildStep: "Extract one function from the exploration notebook into a Python module.",
          aiConnection: "The same discipline governs research-to-production ML transitions.",
          competencyIds: ["DA-INGEST-001", "SE-CODE-001"],
          knowledgeDomains: ["DATA", "PY"],
          minutes: 45,
        }),
      ],
    }),
    mod({
      id: "M4.M2",
      order: 2,
      title: "Cleaning and transformation with pandas",
      purpose: "Make messy data usable.",
      outcomes: ["Clean, join, group, and reshape data.", "Justify every transformation."],
      prerequisites: ["M4.M1"],
      advancesProject: "M4.P2",
      deliverable: "A deterministic, tested pandas pipeline that produces a clean dataset.",
      lessons: [
        lesson({
          id: "M4.M2.L1",
          title: "Selection, filtering, and joins",
          bigIdea: "Data transformation is a small vocabulary applied precisely.",
          whyItMatters: "Fluency here saves hours in every future project.",
          objectives: ["Select rows and columns idiomatically.", "Join two dataframes correctly."],
          keyConcepts: ["boolean indexing", "merge", "index"],
          practice: "Fix three subtly wrong joins.",
          buildStep: "Join two source tables in the pipeline.",
          aiConnection: "Feature engineering is 80% joins.",
          competencyIds: ["DA-CLEAN-001"],
          knowledgeDomains: ["DATA"],
          minutes: 60,
        }),
        lesson({
          id: "M4.M2.L2",
          title: "Group-by and reshape",
          bigIdea: "Aggregation and pivoting turn observations into features.",
          whyItMatters: "This is where signal is created.",
          objectives: ["Group and aggregate.", "Pivot long/wide as needed."],
          prerequisites: ["M4.M2.L1"],
          keyConcepts: ["groupby", "agg", "pivot"],
          practice: "Given a long table, produce three summary aggregations.",
          buildStep: "Add aggregate features to the pipeline.",
          aiConnection: "Every classical ML pipeline aggregates.",
          competencyIds: ["DA-CLEAN-001"],
          knowledgeDomains: ["DATA"],
          minutes: 60,
        }),
        lesson({
          id: "M4.M2.L3",
          title: "Data quality without kidding yourself",
          bigIdea: "Every dataset has lies; naming them is the difference between analyst and vibes.",
          whyItMatters: "Silent quality bugs propagate into models.",
          objectives: ["List common data quality failures.", "Add assertions to a pipeline."],
          prerequisites: ["M4.M2.L2"],
          keyConcepts: ["missingness types", "outlier", "leakage", "assertion"],
          practice: "Given a dataset, write five assertions that would catch a regression.",
          buildStep: "Add data-quality assertions to the pipeline.",
          aiConnection: "Data validation is a first-class MLOps concern.",
          competencyIds: ["DA-CLEAN-001", "RAI-DATA-001"],
          knowledgeDomains: ["DATA", "RESP"],
          minutes: 60,
        }),
      ],
    }),
    mod({
      id: "M4.M3",
      order: 3,
      title: "Relational modelling and SQL",
      purpose: "Learn to think in tables and query them at scale.",
      outcomes: ["Model a domain relationally.", "Write joins, group-bys, and window functions in SQL."],
      prerequisites: ["M4.M2"],
      advancesProject: "M4.P3",
      deliverable: "A small SQLite database with schema, seed data, and a query notebook.",
      lessons: [
        lesson({
          id: "M4.M3.L1",
          title: "Relational modelling for beginners",
          bigIdea: "Split entities into tables, connect them with keys, and normalise until you stop repeating yourself.",
          whyItMatters: "Bad schemas outlive their authors.",
          objectives: ["Sketch a small schema.", "Choose primary and foreign keys."],
          keyConcepts: ["entity", "primary key", "foreign key", "normalisation"],
          practice: "Given a flat CSV, propose a two-table schema.",
          buildStep: "Design and create the flagship database schema.",
          aiConnection: "Retrieval systems and feature stores are relational under the hood.",
          competencyIds: ["DA-SQL-001"],
          knowledgeDomains: ["DATA"],
          minutes: 60,
        }),
        lesson({
          id: "M4.M3.L2",
          title: "SQL you will actually use",
          bigIdea: "SELECT, JOIN, GROUP BY, and window functions cover most working analyst SQL.",
          whyItMatters: "SQL is the lingua franca of data work.",
          objectives: ["Write joins and group-bys.", "Use one window function."],
          prerequisites: ["M4.M3.L1"],
          keyConcepts: ["JOIN", "GROUP BY", "window", "CTE"],
          practice: "Reproduce three pandas summaries in SQL.",
          buildStep: "Author five useful queries against the flagship database.",
          aiConnection: "Feature pipelines and analytics on ML systems both live in SQL.",
          competencyIds: ["DA-SQL-001"],
          knowledgeDomains: ["DATA"],
          minutes: 75,
        }),
      ],
    }),
    mod({
      id: "M4.M4",
      order: 4,
      title: "Visualization and narrative",
      purpose: "Communicate findings without lying.",
      outcomes: ["Choose the right chart for the question.", "Publish a short data narrative."],
      prerequisites: ["M4.M3"],
      advancesProject: "M4.P5",
      deliverable: "A deployed data product with charts, narrative, and reproducibility.",
      lessons: [
        lesson({
          id: "M4.M4.L1",
          title: "Chart choice",
          bigIdea: "The chart type is the argument; pick the one that shows the truth simply.",
          whyItMatters: "Bad charts are how honest work becomes misleading.",
          objectives: ["Match five questions to their appropriate chart.", "Reject a chart type when it hides variance."],
          keyConcepts: ["bar", "line", "scatter", "distribution", "small multiples"],
          practice: "Critique three real-world charts, then redraw one.",
          buildStep: "Draft the flagship product's three key charts.",
          aiConnection: "Model evaluation lives on charts; the same rules apply.",
          competencyIds: ["DA-VIZ-001"],
          knowledgeDomains: ["DATA"],
          minutes: 60,
        }),
        lesson({
          id: "M4.M4.L2",
          title: "Publishing a data narrative",
          bigIdea: "A data product is a claim, supported by charts, backed by a pipeline.",
          whyItMatters: "Making findings public is the ultimate quality gate.",
          objectives: ["Write a short, honest data narrative.", "Publish it alongside the pipeline."],
          prerequisites: ["M4.M4.L1"],
          keyConcepts: ["reproducibility", "narrative structure", "caveat"],
          practice: "Draft caveats sections for three imaginary claims.",
          buildStep: "Deploy the flagship data product.",
          aiConnection: "Model cards and RAG evaluation reports follow the same shape.",
          competencyIds: ["DA-VIZ-001", "COM-WRITE-001", "RAI-LIT-001"],
          knowledgeDomains: ["DATA", "RESP"],
          minutes: 60,
        }),
      ],
    }),
  ],
});
