import { lesson, module as mod, project, milestone } from "../build";

export const M5 = milestone({
  id: "05-math-for-ml",
  number: 5,
  title: "Applied Mathematics & Statistics for ML",
  shortTitle: "Math for ML",
  description:
    "Cover the math that actually shows up in ML — linear algebra, calculus for optimization, probability, and statistics — inside code and simulations.",
  entryState: "Learner is data-fluent and comfortable in Python.",
  exitCapability:
    "Learner can reason about vectors, gradients, distributions, and uncertainty, and implement gradient descent and a small statistical report from scratch.",
  prerequisiteMilestones: ["04-data-fluency"],
  competencyIds: ["MA-LINALG-001", "MA-CALC-001", "PS-DIST-001", "PS-INFER-001"],
  knowledgeDomains: ["MATH", "STAT", "PY"],
  projects: [
    project("M5.P1", "Linear algebra playground", "small", 8),
    project("M5.P2", "Gradient descent from scratch", "small", 10),
    project("M5.P3", "Probability & simulation lab", "small", 8),
    project("M5.P4", "Flagship: Statistical report app", "medium", 20, true),
  ],
  flagshipProjectId: "M5.P4",
  gate: "A deployed statistical report app that computes and honestly communicates uncertainty on a real dataset.",
  estimatedHours: { min: 45, max: 65 },
  modules: [
    mod({
      id: "M5.M1",
      order: 1,
      title: "Linear algebra you can see",
      purpose: "Build intuition for vectors, matrices, and dot products.",
      outcomes: ["Interpret a matrix as a set of column vectors.", "Compute a dot product by hand and in NumPy."],
      advancesProject: "M5.P1",
      deliverable: "Interactive linear algebra playground notebook.",
      lessons: [
        lesson({
          id: "M5.M1.L1",
          title: "Vectors as arrows and as data",
          bigIdea: "A vector is a list of numbers, and also a direction.",
          whyItMatters: "This dual view underlies embeddings and gradients.",
          objectives: ["Add, scale, and dot two vectors.", "Explain cosine similarity in one paragraph."],
          keyConcepts: ["vector", "scalar", "dot product", "norm", "cosine similarity"],
          practice: "Predict, then verify, the cosine similarity of three vector pairs.",
          buildStep: "Implement dot product and cosine similarity in NumPy.",
          aiConnection: "Cosine similarity is the workhorse of semantic search.",
          competencyIds: ["MA-LINALG-001"],
          knowledgeDomains: ["MATH"],
          minutes: 60,
        }),
        lesson({
          id: "M5.M1.L2",
          title: "Matrices as transformations",
          bigIdea: "A matrix is a linear function on vectors.",
          whyItMatters: "Every neural layer is (roughly) a matrix.",
          objectives: ["Multiply two matrices.", "Interpret shape mismatches."],
          prerequisites: ["M5.M1.L1"],
          keyConcepts: ["matmul", "shape", "identity", "rank (intuition)"],
          practice: "Given shape errors from three NumPy snippets, fix each.",
          buildStep: "Implement a small 2D transformation demo.",
          aiConnection: "Matmul is 90% of deep learning FLOPs.",
          competencyIds: ["MA-LINALG-001"],
          knowledgeDomains: ["MATH"],
          minutes: 60,
        }),
      ],
    }),
    mod({
      id: "M5.M2",
      order: 2,
      title: "Calculus for optimization",
      purpose: "Understand gradient descent enough to build one.",
      outcomes: ["Explain what a derivative measures.", "Implement gradient descent for a simple loss."],
      prerequisites: ["M5.M1"],
      advancesProject: "M5.P2",
      deliverable: "Gradient descent from scratch on a small dataset.",
      lessons: [
        lesson({
          id: "M5.M2.L1",
          title: "Derivatives, honestly",
          bigIdea: "The derivative tells you which way is downhill.",
          whyItMatters: "This is the entire trick behind model training.",
          objectives: ["Compute a derivative numerically.", "Interpret a loss landscape."],
          keyConcepts: ["slope", "loss", "step size"],
          practice: "Given a plotted loss, predict where GD converges.",
          buildStep: "Write a numerical derivative function.",
          aiConnection: "Backpropagation is the chain rule applied at scale.",
          competencyIds: ["MA-CALC-001"],
          knowledgeDomains: ["MATH"],
          minutes: 60,
        }),
        lesson({
          id: "M5.M2.L2",
          title: "Gradient descent by hand",
          bigIdea: "GD is: pick a starting point, step downhill, repeat.",
          whyItMatters: "Everything else is engineering.",
          objectives: ["Implement GD for linear regression.", "Diagnose divergence."],
          prerequisites: ["M5.M2.L1"],
          keyConcepts: ["gradient", "learning rate", "convergence"],
          practice: "Given three learning rates, predict which converges.",
          buildStep: "Fit a linear model to real data with hand-rolled GD.",
          aiConnection: "Same mechanic runs every neural network on Earth.",
          competencyIds: ["MA-CALC-001", "ML-BASE-001"],
          knowledgeDomains: ["MATH", "ML"],
          minutes: 75,
        }),
      ],
    }),
    mod({
      id: "M5.M3",
      order: 3,
      title: "Probability and statistics that matter",
      purpose: "Give the learner enough probability to reason about uncertainty and evaluation.",
      outcomes: ["Reason about distributions.", "Estimate uncertainty from a sample."],
      prerequisites: ["M5.M2"],
      advancesProject: "M5.P4",
      deliverable: "Statistical report app with confidence intervals and honest caveats.",
      lessons: [
        lesson({
          id: "M5.M3.L1",
          title: "Distributions in code",
          bigIdea: "A distribution is a machine that produces numbers with rules.",
          whyItMatters: "Reasoning about noise is the entire game in evaluation.",
          objectives: ["Sample from three common distributions.", "Read a histogram critically."],
          keyConcepts: ["random variable", "PMF/PDF", "mean vs median"],
          practice: "Predict, then plot, three histograms.",
          buildStep: "Simulate the flagship dataset's noise.",
          aiConnection: "Model outputs are random variables; treat them that way.",
          competencyIds: ["PS-DIST-001"],
          knowledgeDomains: ["STAT"],
          minutes: 60,
        }),
        lesson({
          id: "M5.M3.L2",
          title: "Sampling and confidence",
          bigIdea: "You can quantify what you don't know from what you saw.",
          whyItMatters: "Point estimates without intervals mislead.",
          objectives: ["Bootstrap a confidence interval.", "Explain a CI in plain language."],
          prerequisites: ["M5.M3.L1"],
          keyConcepts: ["sampling", "bootstrap", "confidence interval"],
          practice: "Given three claims, rewrite each with an honest interval.",
          buildStep: "Add bootstrapped CIs to the report app.",
          aiConnection: "Every model metric deserves an interval, not a single number.",
          competencyIds: ["PS-INFER-001", "RAI-LIT-001"],
          knowledgeDomains: ["STAT", "RESP"],
          minutes: 60,
        }),
        lesson({
          id: "M5.M3.L3",
          title: "Comparisons that don't lie",
          bigIdea: "A difference is a claim; it needs an estimate and an interval.",
          whyItMatters: "Model A vs Model B decisions are made this way.",
          objectives: ["Compare two groups with a bootstrapped difference.", "Interpret a p-value at a survival level."],
          prerequisites: ["M5.M3.L2"],
          keyConcepts: ["difference in means", "bootstrap difference", "p-value (survival)"],
          practice: "Given two model score distributions, decide whether Model B is better.",
          buildStep: "Add an A/B comparison to the report app.",
          aiConnection: "Every offline eval, at heart, is this comparison.",
          competencyIds: ["PS-INFER-001"],
          knowledgeDomains: ["STAT"],
          minutes: 60,
        }),
      ],
    }),
  ],
});
