import { lesson, module as mod, project, milestone } from "../build";

export const M6 = milestone({
  id: "06-classical-ml",
  number: 6,
  title: "Classical Machine Learning",
  shortTitle: "Classical ML",
  description: "Frame problems as ML tasks, train and evaluate models, and ship a first predictive service.",
  entryState: "Learner has math foundations, data fluency, and professional Python.",
  exitCapability:
    "Learner can frame supervised problems, build reproducible pipelines with scikit-learn, evaluate honestly, and deploy a predictive service.",
  prerequisiteMilestones: ["05-math-for-ml"],
  competencyIds: ["ML-FRAME-001", "ML-PIPE-001", "ML-EVAL-001", "ML-INTERP-001"],
  knowledgeDomains: ["ML", "DATA", "STAT", "RESP"],
  projects: [
    project("M6.P1", "First supervised model, end-to-end", "small", 10),
    project("M6.P2", "Feature engineering & pipelines", "small", 10),
    project("M6.P3", "Model comparison & selection", "small", 8),
    project("M6.P4", "Regression + interpretability project", "medium", 15),
    project("M6.P5", "Flagship: Predictive service", "medium", 25, true),
  ],
  flagshipProjectId: "M6.P5",
  gate: "A deployed predictive service with a documented model, honest evaluation, and a written limitations section.",
  estimatedHours: { min: 60, max: 90 },
  modules: [
    mod({
      id: "M6.M1",
      order: 1,
      title: "Framing a problem as ML",
      purpose: "Learn to decide whether ML is the right tool and what task type fits.",
      outcomes: ["Distinguish classification, regression, and ranking.", "Draft a problem framing document."],
      advancesProject: "M6.P1",
      deliverable: "One-page framing document for the flagship problem.",
      lessons: [
        lesson({
          id: "M6.M1.L1",
          title: "When to use ML at all",
          bigIdea: "ML is right when the pattern is real, the data is available, and mistakes are affordable.",
          whyItMatters: "Cheap heuristics beat expensive models more often than beginners admit.",
          objectives: ["List three cases where ML is the wrong tool.", "State the null-model baseline for a problem."],
          keyConcepts: ["baseline", "target", "cost of error"],
          practice: "For three product ideas, decide 'ML or rule'.",
          buildStep: "Draft the flagship framing.",
          aiConnection: "This decision is the top of every real AI system's design doc.",
          competencyIds: ["ML-FRAME-001", "PROD-USER-001"],
          knowledgeDomains: ["ML"],
          minutes: 45,
        }),
        lesson({
          id: "M6.M1.L2",
          title: "Supervised task shapes",
          bigIdea: "Most ML you'll ship is supervised: classification or regression.",
          whyItMatters: "The task shape drives everything downstream.",
          objectives: ["Classify five problems by task type.", "Pick a first metric for each."],
          prerequisites: ["M6.M1.L1"],
          keyConcepts: ["classification", "regression", "metric selection"],
          practice: "For each of five problems, pick a metric and defend it.",
          buildStep: "Choose the task and metric for the flagship.",
          aiConnection: "Even LLM tasks reduce to these shapes under the hood.",
          competencyIds: ["ML-FRAME-001", "ML-EVAL-001"],
          knowledgeDomains: ["ML"],
          minutes: 45,
        }),
      ],
    }),
    mod({
      id: "M6.M2",
      order: 2,
      title: "End-to-end pipelines with scikit-learn",
      purpose: "Ship one honest supervised model, top to bottom.",
      outcomes: ["Build a scikit-learn Pipeline.", "Cross-validate correctly."],
      prerequisites: ["M6.M1"],
      advancesProject: "M6.P2",
      deliverable: "A reproducible sklearn Pipeline with saved artifacts.",
      lessons: [
        lesson({
          id: "M6.M2.L1",
          title: "Train/validation/test",
          bigIdea: "You cannot trust results measured on the data you fit.",
          whyItMatters: "Leakage silently ruins projects.",
          objectives: ["Split data three ways.", "Detect leakage in a scenario."],
          keyConcepts: ["train/val/test", "leakage", "cross-validation"],
          practice: "Given five scenarios, identify the two that leak.",
          buildStep: "Add a clean split to the flagship pipeline.",
          aiConnection: "Every LLM eval requires the same discipline.",
          competencyIds: ["ML-PIPE-001", "ML-EVAL-001"],
          knowledgeDomains: ["ML"],
          minutes: 60,
        }),
        lesson({
          id: "M6.M2.L2",
          title: "Preprocessing and Pipeline",
          bigIdea: "Preprocessing belongs inside the pipeline, not before it.",
          whyItMatters: "This is the difference between a real model and a leaky notebook.",
          objectives: ["Compose ColumnTransformer + estimator.", "Persist and reload the pipeline."],
          prerequisites: ["M6.M2.L1"],
          keyConcepts: ["Pipeline", "ColumnTransformer", "joblib"],
          practice: "Refactor a leaky notebook into a Pipeline.",
          buildStep: "Ship the flagship's Pipeline.",
          aiConnection: "Feature stores extend this idea across teams.",
          competencyIds: ["ML-PIPE-001"],
          knowledgeDomains: ["ML"],
          minutes: 75,
        }),
      ],
    }),
    mod({
      id: "M6.M3",
      order: 3,
      title: "Evaluation and interpretability",
      purpose: "Understand the model well enough to defend it.",
      outcomes: ["Read confusion matrices and calibration plots.", "Explain a prediction with SHAP or coefficients."],
      prerequisites: ["M6.M2"],
      advancesProject: "M6.P4",
      deliverable: "Model card + interpretability report for the flagship model.",
      lessons: [
        lesson({
          id: "M6.M3.L1",
          title: "Metrics beyond accuracy",
          bigIdea: "Accuracy hides the mistakes that matter.",
          whyItMatters: "Class imbalance turns 'accuracy' into a lie.",
          objectives: ["Read precision, recall, and ROC.", "Choose a metric matching business cost."],
          keyConcepts: ["precision", "recall", "F1", "ROC-AUC", "calibration"],
          practice: "Given four confusion matrices, pick the least bad model for a stated cost structure.",
          buildStep: "Evaluate the flagship with the right metric.",
          aiConnection: "LLM evals borrow the same vocabulary.",
          competencyIds: ["ML-EVAL-001"],
          knowledgeDomains: ["ML", "STAT"],
          minutes: 60,
        }),
        lesson({
          id: "M6.M3.L2",
          title: "Explaining a prediction",
          bigIdea: "A model you can't explain is one you can't ship responsibly.",
          whyItMatters: "Interpretability is a stakeholder requirement, not decoration.",
          objectives: ["Explain a prediction with feature importances or SHAP.", "State three failure modes."],
          prerequisites: ["M6.M3.L1"],
          keyConcepts: ["feature importance", "SHAP", "counterfactual"],
          practice: "Explain three predictions to a non-technical stakeholder.",
          buildStep: "Add an explanation panel to the flagship service.",
          aiConnection: "Model cards and LLM evals lean on the same skill.",
          competencyIds: ["ML-INTERP-001", "RAI-LIT-001"],
          knowledgeDomains: ["ML", "RESP"],
          minutes: 60,
        }),
      ],
    }),
    mod({
      id: "M6.M4",
      order: 4,
      title: "Shipping a predictive service",
      purpose: "Turn a model into an HTTP service.",
      outcomes: ["Serve a model behind an API.", "Write a model card."],
      prerequisites: ["M6.M3"],
      advancesProject: "M6.P5",
      deliverable: "Deployed predictive service with a model card.",
      lessons: [
        lesson({
          id: "M6.M4.L1",
          title: "From artifact to endpoint",
          bigIdea: "A model in production is an HTTP endpoint with contracts.",
          whyItMatters: "This is the shape all future AI services take.",
          objectives: ["Wrap a model in a small web framework.", "Version the input schema."],
          keyConcepts: ["FastAPI (or Flask)", "input schema", "versioning"],
          practice: "Given a bad API, propose a versioning strategy.",
          buildStep: "Serve the flagship model behind a simple HTTP endpoint.",
          aiConnection: "LLM apps live behind the exact same shape.",
          competencyIds: ["SYS-DEPLOY-001", "SE-CODE-001"],
          knowledgeDomains: ["ML", "MLOPS"],
          minutes: 60,
        }),
        lesson({
          id: "M6.M4.L2",
          title: "Model cards and honest limitations",
          bigIdea: "A model card names what the model is, is for, and is not for.",
          whyItMatters: "Honest limitations are a professional signal.",
          objectives: ["Write a model card.", "List three known limitations."],
          prerequisites: ["M6.M4.L1"],
          keyConcepts: ["model card", "intended use", "limitation"],
          practice: "Redline a bad model card.",
          buildStep: "Publish the model card alongside the service.",
          aiConnection: "System cards for LLM apps are model cards with more surfaces.",
          competencyIds: ["RAI-LIT-001", "COM-WRITE-001"],
          knowledgeDomains: ["RESP"],
          minutes: 45,
        }),
      ],
    }),
  ],
});
