import { lesson, module as mod, project, milestone } from "../build";

export const M7 = milestone({
  id: "07-deep-learning",
  number: 7,
  title: "Deep Learning",
  shortTitle: "Deep Learning",
  description: "Build, train, and evaluate neural networks in PyTorch across images and text.",
  entryState: "Learner ships classical ML services and understands gradients.",
  exitCapability:
    "Learner can implement an MLP from scratch, train modern architectures for images and text, track experiments reproducibly, and deploy a trained-model API.",
  prerequisiteMilestones: ["06-classical-ml"],
  competencyIds: ["DL-ARCH-001", "DL-TRAIN-001", "DL-REPRO-001", "DL-DEPLOY-001"],
  knowledgeDomains: ["DL", "ML", "MATH"],
  projects: [
    project("M7.P1", "MLP from scratch, then in PyTorch", "small", 10),
    project("M7.P2", "Image classification project", "medium", 15),
    project("M7.P3", "Text classification project", "medium", 15),
    project("M7.P4", "Experiment tracking & reproducibility", "small", 8),
    project("M7.P5", "Flagship: Trained-model API", "medium", 25, true),
  ],
  flagshipProjectId: "M7.P5",
  gate: "A deployed trained-model API with experiment history, reproducible training, and honest evaluation.",
  estimatedHours: { min: 70, max: 100 },
  modules: [
    mod({
      id: "M7.M1",
      order: 1,
      title: "Neural networks from first principles",
      purpose: "Build an MLP by hand before reaching for a framework.",
      outcomes: ["Explain forward and backward pass.", "Train a tiny MLP without a framework."],
      advancesProject: "M7.P1",
      deliverable: "A hand-rolled MLP notebook.",
      lessons: [
        lesson({
          id: "M7.M1.L1",
          title: "Neurons, layers, activations",
          bigIdea: "A neural net is stacked linear + nonlinear transforms.",
          whyItMatters: "Every architecture on Earth is a variation on this pattern.",
          objectives: ["Compute a forward pass by hand.", "Explain why nonlinearity matters."],
          keyConcepts: ["neuron", "activation", "layer", "hidden dim"],
          practice: "Predict outputs of a 2-layer net with tiny weights.",
          buildStep: "Implement forward pass in NumPy.",
          aiConnection: "Transformers are (still) stacked linear + nonlinear + attention.",
          competencyIds: ["DL-ARCH-001"],
          knowledgeDomains: ["DL", "MATH"],
          minutes: 60,
        }),
        lesson({
          id: "M7.M1.L2",
          title: "Backprop, honestly",
          bigIdea: "Backprop is the chain rule applied bottom-up over a computation graph.",
          whyItMatters: "You can't debug what you can't picture.",
          objectives: ["Derive one layer's gradient by hand.", "Implement backward pass for a 2-layer MLP."],
          prerequisites: ["M7.M1.L1"],
          keyConcepts: ["chain rule", "computation graph", "autograd"],
          practice: "Hand-check backprop against numerical gradients.",
          buildStep: "Train the hand-rolled MLP on toy data.",
          aiConnection: "Autograd is this, at industrial scale.",
          competencyIds: ["DL-ARCH-001", "MA-CALC-001"],
          knowledgeDomains: ["DL", "MATH"],
          minutes: 75,
        }),
      ],
    }),
    mod({
      id: "M7.M2",
      order: 2,
      title: "PyTorch fluency",
      purpose: "Move to a real framework without losing understanding.",
      outcomes: ["Author, train, and evaluate a model in PyTorch.", "Move computation to GPU when available."],
      prerequisites: ["M7.M1"],
      advancesProject: "M7.P2",
      deliverable: "Image classifier trained in PyTorch with logging.",
      lessons: [
        lesson({
          id: "M7.M2.L1",
          title: "Tensors, autograd, devices",
          bigIdea: "PyTorch is NumPy + gradients + GPUs.",
          whyItMatters: "Understanding this trio unlocks the ecosystem.",
          objectives: ["Manipulate tensors.", "Move a model between CPU and GPU."],
          keyConcepts: ["tensor", "autograd", "device"],
          practice: "Fix three shape / device bugs.",
          buildStep: "Port the hand-rolled MLP to PyTorch.",
          aiConnection: "Every deep model you'll ever load is a PyTorch tensor tree.",
          competencyIds: ["DL-ARCH-001"],
          knowledgeDomains: ["DL"],
          minutes: 60,
        }),
        lesson({
          id: "M7.M2.L2",
          title: "Training loops that work",
          bigIdea: "A training loop is: forward, loss, backward, step, log.",
          whyItMatters: "Every DL bug lives in one of these five steps.",
          objectives: ["Write a training loop.", "Log per-epoch metrics."],
          prerequisites: ["M7.M2.L1"],
          keyConcepts: ["optimizer", "loss", "scheduler", "logging"],
          practice: "Given a broken loop, identify the missing step.",
          buildStep: "Train the flagship model with a real loop.",
          aiConnection: "This loop scales to LLM pretraining conceptually unchanged.",
          competencyIds: ["DL-TRAIN-001"],
          knowledgeDomains: ["DL"],
          minutes: 75,
        }),
      ],
    }),
    mod({
      id: "M7.M3",
      order: 3,
      title: "Vision and text with pretrained models",
      purpose: "Adapt modern architectures with transfer learning.",
      outcomes: ["Fine-tune a pretrained image model.", "Fine-tune a pretrained text encoder."],
      prerequisites: ["M7.M2"],
      advancesProject: "M7.P3",
      deliverable: "Image and text classifiers with published evaluations.",
      lessons: [
        lesson({
          id: "M7.M3.L1",
          title: "Transfer learning",
          bigIdea: "Someone else did the expensive part; you adapt.",
          whyItMatters: "This is the only way ordinary teams train modern models.",
          objectives: ["Load a pretrained model.", "Fine-tune it for a new dataset."],
          keyConcepts: ["pretrained", "fine-tune", "frozen layers"],
          practice: "Given a task, choose whether to fine-tune or use as-is.",
          buildStep: "Fine-tune an image model on a small dataset.",
          aiConnection: "LLM fine-tuning is the same idea at bigger scale.",
          competencyIds: ["DL-TRAIN-001"],
          knowledgeDomains: ["DL"],
          minutes: 75,
        }),
        lesson({
          id: "M7.M3.L2",
          title: "Text encoders",
          bigIdea: "A text encoder turns tokens into vectors you can classify.",
          whyItMatters: "This bridges DL and LLM work.",
          objectives: ["Tokenise and embed a batch.", "Fine-tune for classification."],
          prerequisites: ["M7.M3.L1"],
          keyConcepts: ["tokenizer", "embedding", "pooling"],
          practice: "Explain what a tokenizer did to a given sentence.",
          buildStep: "Ship a text classifier on real data.",
          aiConnection: "Embeddings are the same trick used in retrieval.",
          competencyIds: ["DL-ARCH-001", "LLM-BASE-001"],
          knowledgeDomains: ["DL", "LLM"],
          minutes: 75,
        }),
      ],
    }),
    mod({
      id: "M7.M4",
      order: 4,
      title: "Reproducibility and deployment",
      purpose: "Make experiments trackable and put a model behind an API.",
      outcomes: ["Track experiments and seeds.", "Serve a trained model."],
      prerequisites: ["M7.M3"],
      advancesProject: "M7.P5",
      deliverable: "Trained-model API with reproducible training runbook.",
      lessons: [
        lesson({
          id: "M7.M4.L1",
          title: "Experiment tracking",
          bigIdea: "A run you can't identify is a run you didn't do.",
          whyItMatters: "Undocumented experiments waste weeks.",
          objectives: ["Log runs with a tracker.", "Reproduce a past run."],
          keyConcepts: ["run", "seed", "artifact"],
          practice: "Reconstruct a run from its metadata alone.",
          buildStep: "Wire experiment tracking into training.",
          aiConnection: "MLOps demands this for every deployed model.",
          competencyIds: ["DL-REPRO-001"],
          knowledgeDomains: ["DL", "MLOPS"],
          minutes: 60,
        }),
        lesson({
          id: "M7.M4.L2",
          title: "Serving a trained model",
          bigIdea: "Deployment is packaging weights + preprocessing + an interface.",
          whyItMatters: "Model inference at inference-time is a distinct engineering discipline.",
          objectives: ["Deploy a model as an API.", "Measure latency."],
          prerequisites: ["M7.M4.L1"],
          keyConcepts: ["inference server", "batching", "latency"],
          practice: "Given latency measurements, propose one improvement.",
          buildStep: "Deploy the flagship trained-model API.",
          aiConnection: "This is the substrate every LLM app runs on.",
          competencyIds: ["DL-DEPLOY-001", "SYS-DEPLOY-001"],
          knowledgeDomains: ["DL", "MLOPS"],
          minutes: 75,
        }),
      ],
    }),
  ],
});
