import { lesson, module as mod, project, milestone } from "../build";

export const M8 = milestone({
  id: "08-llms-and-genai",
  number: 8,
  title: "LLMs & Applied Generative AI",
  shortTitle: "LLMs & GenAI",
  description:
    "Use, evaluate, and engineer around large language models. Build retrieval, structured outputs, tools, agents, and a full RAG assistant.",
  entryState: "Learner ships trained-model APIs and reasons about evaluation.",
  exitCapability:
    "Learner can build LLM-powered products with prompt engineering, structured extraction, retrieval, tool use, and rigorous evaluations.",
  prerequisiteMilestones: ["07-deep-learning"],
  competencyIds: ["LLM-USE-001", "LLM-STRUCT-001", "RTA-RAG-001", "RTA-TOOL-001", "LLM-EVAL-001"],
  knowledgeDomains: ["LLM", "APP", "RESP"],
  projects: [
    project("M8.P1", "Prompt engineering lab", "small", 6),
    project("M8.P2", "Structured-output extraction service", "small", 10),
    project("M8.P3", "Embeddings + semantic search", "medium", 12),
    project("M8.P4", "Tool-using / agentic workflow", "medium", 15),
    project("M8.P5", "LLM evaluation suite", "small", 10),
    project("M8.P6", "Flagship: RAG assistant with evaluations", "flagship", 40, true),
  ],
  flagshipProjectId: "M8.P6",
  gate: "A deployed RAG assistant with an evaluation suite, honest limitations, and cost tracking.",
  estimatedHours: { min: 90, max: 130 },
  modules: [
    mod({
      id: "M8.M1",
      order: 1,
      title: "LLMs as engineering components",
      purpose: "Meet LLMs as stochastic HTTP services with capabilities and failure modes.",
      outcomes: ["Call an LLM API.", "Reason about non-determinism, context, and cost."],
      advancesProject: "M8.P1",
      deliverable: "A prompt engineering lab notebook.",
      lessons: [
        lesson({
          id: "M8.M1.L1",
          title: "What an LLM is, mechanistically",
          bigIdea: "An LLM is a next-token predictor trained on lots of text.",
          whyItMatters: "This picture explains most 'weird' behaviour.",
          objectives: ["Explain tokens, context, and sampling.", "Predict why a given prompt fails."],
          keyConcepts: ["token", "context window", "temperature", "sampling"],
          practice: "Given three failure cases, diagnose which is a context, prompt, or sampling issue.",
          buildStep: "Instrument prompt/response logging in the lab.",
          aiConnection: "This is the substrate for every downstream feature this milestone builds.",
          competencyIds: ["LLM-USE-001"],
          knowledgeDomains: ["LLM"],
          minutes: 60,
        }),
        lesson({
          id: "M8.M1.L2",
          title: "Prompt engineering as design",
          bigIdea: "A prompt is a specification the model interprets probabilistically.",
          whyItMatters: "Small prompt changes swing quality more than most model swaps.",
          objectives: ["Apply few-shot, role, and format constraints.", "Diff two prompts by output distribution, not vibes."],
          prerequisites: ["M8.M1.L1"],
          keyConcepts: ["system prompt", "few-shot", "output contract"],
          practice: "Iterate a prompt across three versions with logged outputs.",
          buildStep: "Finish the prompt lab.",
          aiConnection: "The rest of the milestone assumes this fluency.",
          competencyIds: ["LLM-USE-001"],
          knowledgeDomains: ["LLM"],
          minutes: 60,
        }),
      ],
    }),
    mod({
      id: "M8.M2",
      order: 2,
      title: "Structured outputs and tool use",
      purpose: "Turn LLMs into components that talk to code.",
      outcomes: ["Extract structured JSON reliably.", "Let a model call tools safely."],
      prerequisites: ["M8.M1"],
      advancesProject: "M8.P4",
      deliverable: "Structured extraction service and a tool-using workflow.",
      lessons: [
        lesson({
          id: "M8.M2.L1",
          title: "Structured outputs",
          bigIdea: "Free text is a bug; schemas are a feature.",
          whyItMatters: "Downstream code needs parseable outputs.",
          objectives: ["Define a JSON schema for outputs.", "Handle schema failures."],
          keyConcepts: ["JSON schema", "validator", "retry"],
          practice: "Given a schema, write three tests that a bad extraction must fail.",
          buildStep: "Ship the extraction service.",
          aiConnection: "This shape is used by nearly every LLM feature in production.",
          competencyIds: ["LLM-STRUCT-001", "SE-TEST-001"],
          knowledgeDomains: ["LLM", "APP"],
          minutes: 75,
        }),
        lesson({
          id: "M8.M2.L2",
          title: "Tools and agents, carefully",
          bigIdea: "A model that can call tools is more powerful and more dangerous.",
          whyItMatters: "Autonomy without evaluation is unsafe.",
          objectives: ["Wire a tool call.", "Bound autonomy with rules."],
          prerequisites: ["M8.M2.L1"],
          keyConcepts: ["tool call", "planner", "sandbox"],
          practice: "Design three refusal rules for a proposed agent.",
          buildStep: "Ship a bounded tool-using workflow.",
          aiConnection: "This is the beating heart of every serious 'agent' product.",
          competencyIds: ["RTA-TOOL-001", "RAI-LIT-001"],
          knowledgeDomains: ["LLM", "APP", "RESP"],
          minutes: 75,
        }),
      ],
    }),
    mod({
      id: "M8.M3",
      order: 3,
      title: "Embeddings and retrieval",
      purpose: "Bring the right context to the model at inference time.",
      outcomes: ["Build a semantic search index.", "Compose retrieval into a chat flow."],
      prerequisites: ["M8.M2"],
      advancesProject: "M8.P3",
      deliverable: "Semantic search service over a real corpus.",
      lessons: [
        lesson({
          id: "M8.M3.L1",
          title: "Embeddings, honestly",
          bigIdea: "Embeddings map meaning to geometry.",
          whyItMatters: "This is the enabling trick behind retrieval.",
          objectives: ["Embed and index a corpus.", "Query with cosine similarity."],
          keyConcepts: ["embedding", "vector store", "cosine similarity", "chunking"],
          practice: "Choose a chunking strategy for a given corpus, then defend it.",
          buildStep: "Index the flagship corpus.",
          aiConnection: "Retrieval powers most production LLM systems today.",
          competencyIds: ["RTA-RAG-001", "MA-LINALG-001"],
          knowledgeDomains: ["LLM", "APP"],
          minutes: 75,
        }),
        lesson({
          id: "M8.M3.L2",
          title: "RAG end-to-end",
          bigIdea: "RAG is: retrieve relevant context, prompt, generate, cite.",
          whyItMatters: "This is the flagship architecture.",
          objectives: ["Compose retrieval + generation.", "Return citations."],
          prerequisites: ["M8.M3.L1"],
          keyConcepts: ["retriever", "generator", "citation"],
          practice: "Given a bad RAG answer, diagnose retrieval vs generation.",
          buildStep: "Assemble the RAG assistant v0.",
          aiConnection: "The flagship rests on this lesson.",
          competencyIds: ["RTA-RAG-001"],
          knowledgeDomains: ["LLM", "APP"],
          minutes: 90,
        }),
      ],
    }),
    mod({
      id: "M8.M4",
      order: 4,
      title: "Evaluating LLM systems",
      purpose: "Evaluate LLM apps like real software.",
      outcomes: ["Design a task-specific eval.", "Report results honestly."],
      prerequisites: ["M8.M3"],
      advancesProject: "M8.P6",
      deliverable: "An evaluation suite that gates flagship releases.",
      lessons: [
        lesson({
          id: "M8.M4.L1",
          title: "What to measure",
          bigIdea: "You cannot ship what you cannot measure.",
          whyItMatters: "Vibes-based LLM eval is the industry's biggest failure mode.",
          objectives: ["Design a golden set.", "Choose automatic + human eval axes."],
          keyConcepts: ["golden set", "rubric", "LLM-as-judge (with caveats)"],
          practice: "Design an eval for a specified task in one page.",
          buildStep: "Build the golden set for the flagship.",
          aiConnection: "This is the professional bar for RAG systems.",
          competencyIds: ["LLM-EVAL-001", "RAI-LIT-001"],
          knowledgeDomains: ["LLM", "APP", "RESP"],
          minutes: 75,
        }),
        lesson({
          id: "M8.M4.L2",
          title: "Running and reporting evals",
          bigIdea: "Every prompt or model change requires an eval pass.",
          whyItMatters: "This is how quality survives contact with users.",
          objectives: ["Run the eval suite.", "Report deltas honestly."],
          prerequisites: ["M8.M4.L1"],
          keyConcepts: ["regression", "cost report", "release gate"],
          practice: "Given three eval reports, decide which release to ship.",
          buildStep: "Wire the eval into CI for the flagship.",
          aiConnection: "This gate is what separates prototype and product.",
          competencyIds: ["LLM-EVAL-001", "SE-CI-001"],
          knowledgeDomains: ["LLM", "MLOPS"],
          minutes: 75,
        }),
      ],
    }),
  ],
});
