import { lesson, module as mod, project, milestone } from "../build";

export const M9 = milestone({
  id: "09-mlops-production",
  number: 9,
  title: "MLOps & Production AI Systems",
  shortTitle: "MLOps",
  description:
    "Operate AI systems as real products: observability, cost, versioning, continuous evaluation, and responsible-AI review.",
  entryState: "Learner ships LLM apps with evaluations.",
  exitCapability:
    "Learner runs AI systems in production with observability, cost/perf discipline, versioned data/models, drift monitoring, and a responsible-AI review process.",
  prerequisiteMilestones: ["08-llms-and-genai"],
  competencyIds: ["SYS-OBS-001", "SYS-COST-001", "SYS-VER-001", "SYS-DRIFT-001", "RAI-REVIEW-001"],
  knowledgeDomains: ["MLOPS", "RESP"],
  projects: [
    project("M9.P1", "Observability retrofit", "small", 10),
    project("M9.P2", "Cost & performance engineering", "small", 10),
    project("M9.P3", "Data & model versioning", "small", 10),
    project("M9.P4", "Continuous evaluation & drift", "medium", 15),
    project("M9.P5", "Responsible AI & safety review", "small", 10),
    project("M9.P6", "Flagship: Deployed, monitored AI product", "flagship", 40, true),
  ],
  flagshipProjectId: "M9.P6",
  gate: "A deployed, monitored AI product with dashboards, cost controls, versioning, drift alerts, and a signed responsible-AI review.",
  estimatedHours: { min: 80, max: 120 },
  modules: [
    mod({
      id: "M9.M1",
      order: 1,
      title: "Observability for AI systems",
      purpose: "You cannot operate what you cannot see.",
      outcomes: ["Instrument logs, metrics, and traces.", "Build a minimal dashboard."],
      advancesProject: "M9.P1",
      deliverable: "Dashboard covering latency, error rate, and quality proxy for the flagship product.",
      lessons: [
        lesson({
          id: "M9.M1.L1",
          title: "Logs, metrics, traces",
          bigIdea: "Three signals cover most production questions.",
          whyItMatters: "Without them, incidents are guesswork.",
          objectives: ["Emit structured logs.", "Define three SLIs."],
          keyConcepts: ["structured log", "metric", "trace", "SLI/SLO"],
          practice: "Given an outage, list the queries you'd run.",
          buildStep: "Instrument the flagship product.",
          aiConnection: "AI systems have extra failure modes; the primitives are the same.",
          competencyIds: ["SYS-OBS-001"],
          knowledgeDomains: ["MLOPS"],
          minutes: 60,
        }),
        lesson({
          id: "M9.M1.L2",
          title: "Quality signals in production",
          bigIdea: "Model quality drifts silently; instrument a proxy.",
          whyItMatters: "Latency and errors aren't enough for AI.",
          objectives: ["Define a quality proxy metric.", "Alert on it."],
          prerequisites: ["M9.M1.L1"],
          keyConcepts: ["quality proxy", "shadow eval", "alerting"],
          practice: "Choose a proxy metric for a given LLM feature.",
          buildStep: "Ship a proxy metric for the flagship.",
          aiConnection: "This is the missing piece in most 'monitored' AI products.",
          competencyIds: ["SYS-OBS-001", "LLM-EVAL-001"],
          knowledgeDomains: ["MLOPS"],
          minutes: 60,
        }),
      ],
    }),
    mod({
      id: "M9.M2",
      order: 2,
      title: "Cost, performance, and scale",
      purpose: "Ship AI that a real business can afford.",
      outcomes: ["Measure and reduce inference cost.", "Choose caching and batching wisely."],
      prerequisites: ["M9.M1"],
      advancesProject: "M9.P2",
      deliverable: "Cost-per-request dashboard and a documented performance budget.",
      lessons: [
        lesson({
          id: "M9.M2.L1",
          title: "Cost engineering",
          bigIdea: "Cost is a first-class product requirement for AI.",
          whyItMatters: "Prototypes that cannot afford to serve users are not products.",
          objectives: ["Measure $/request.", "Propose two reductions."],
          keyConcepts: ["cost per request", "caching", "batching", "distillation (mention)"],
          practice: "Given traffic + model choice, estimate monthly cost.",
          buildStep: "Add cost tracking to the flagship.",
          aiConnection: "This decides whether an idea ships.",
          competencyIds: ["SYS-COST-001"],
          knowledgeDomains: ["MLOPS"],
          minutes: 60,
        }),
        lesson({
          id: "M9.M2.L2",
          title: "Latency budgets",
          bigIdea: "User-perceived latency is a product feature.",
          whyItMatters: "Slow AI is unused AI.",
          objectives: ["Set a p95 target.", "Diagnose a slow path."],
          prerequisites: ["M9.M2.L1"],
          keyConcepts: ["p50/p95", "streaming", "cold start"],
          practice: "Given a trace, identify the biggest optimization opportunity.",
          buildStep: "Hit the flagship's latency target.",
          aiConnection: "LLM UX especially depends on streaming and warm-cache design.",
          competencyIds: ["SYS-COST-001", "SYS-DEPLOY-001"],
          knowledgeDomains: ["MLOPS"],
          minutes: 60,
        }),
      ],
    }),
    mod({
      id: "M9.M3",
      order: 3,
      title: "Versioning and continuous evaluation",
      purpose: "Version everything so you can improve safely.",
      outcomes: ["Version data, models, and prompts.", "Run continuous evaluation on production traffic."],
      prerequisites: ["M9.M2"],
      advancesProject: "M9.P4",
      deliverable: "Versioned data/model/prompt pipeline with a continuous-evaluation job.",
      lessons: [
        lesson({
          id: "M9.M3.L1",
          title: "What to version",
          bigIdea: "Code, data, model, prompts — all four must be versioned.",
          whyItMatters: "Unversioned assets defeat every other MLOps practice.",
          objectives: ["Version a dataset.", "Pin a model."],
          keyConcepts: ["dataset version", "model registry", "prompt version"],
          practice: "Diagnose which of four failures was caused by unversioned assets.",
          buildStep: "Version the flagship pipeline end-to-end.",
          aiConnection: "This is table stakes for regulated AI work.",
          competencyIds: ["SYS-VER-001"],
          knowledgeDomains: ["MLOPS"],
          minutes: 60,
        }),
        lesson({
          id: "M9.M3.L2",
          title: "Drift and continuous eval",
          bigIdea: "Reality changes; your model doesn't unless you make it.",
          whyItMatters: "Silent drift is the top cause of long-run AI failure.",
          objectives: ["Detect feature or output drift.", "Trigger a retraining or prompt review."],
          prerequisites: ["M9.M3.L1"],
          keyConcepts: ["data drift", "concept drift", "canary release"],
          practice: "Design a drift alert for a specified feature.",
          buildStep: "Wire continuous evaluation into the flagship.",
          aiConnection: "This is the boundary between an AI system and an AI product.",
          competencyIds: ["SYS-DRIFT-001", "LLM-EVAL-001"],
          knowledgeDomains: ["MLOPS"],
          minutes: 75,
        }),
      ],
    }),
    mod({
      id: "M9.M4",
      order: 4,
      title: "Responsible AI in production",
      purpose: "Make responsibility a checklist, not a slogan.",
      outcomes: ["Run a pre-launch safety review.", "Publish a system card."],
      prerequisites: ["M9.M3"],
      advancesProject: "M9.P5",
      deliverable: "Signed pre-launch responsible-AI review and a system card.",
      lessons: [
        lesson({
          id: "M9.M4.L1",
          title: "Threat modelling for AI",
          bigIdea: "Every AI feature has an abuse surface; name it before users do.",
          whyItMatters: "Post-launch fixes are expensive and public.",
          objectives: ["List abuse cases.", "Propose mitigations for the top three."],
          keyConcepts: ["threat model", "misuse", "PII", "prompt injection"],
          practice: "Threat-model a given LLM feature in one page.",
          buildStep: "Threat-model the flagship product.",
          aiConnection: "Prompt injection is now a top-3 threat for LLM apps.",
          competencyIds: ["RAI-REVIEW-001", "RAI-LIT-001"],
          knowledgeDomains: ["RESP"],
          minutes: 60,
        }),
        lesson({
          id: "M9.M4.L2",
          title: "System cards and rollout",
          bigIdea: "Ship with a written system card and a staged rollout, or don't ship.",
          whyItMatters: "This is the responsible bar for real products.",
          objectives: ["Author a system card.", "Design a staged rollout."],
          prerequisites: ["M9.M4.L1"],
          keyConcepts: ["system card", "canary", "kill switch"],
          practice: "Redline a bad system card.",
          buildStep: "Publish the flagship's system card.",
          aiConnection: "Regulators increasingly require this artifact.",
          competencyIds: ["RAI-REVIEW-001", "COM-WRITE-001"],
          knowledgeDomains: ["RESP"],
          minutes: 60,
        }),
      ],
    }),
  ],
});
