import { lesson, module as mod, project, milestone } from "../build";

export const M10 = milestone({
  id: "10-capstone",
  number: 10,
  title: "Capstone, Specialization & Career Launch",
  shortTitle: "Capstone",
  description:
    "Ship an original AI product, choose a specialisation, and prepare for professional practice.",
  entryState: "Learner ships deployed, monitored AI systems with responsible-AI review.",
  exitCapability:
    "Learner has an original, defensible AI product in the wild, a specialisation deep-dive, and a portfolio and story that stand up to a professional interview.",
  prerequisiteMilestones: ["09-mlops-production"],
  competencyIds: ["PROD-USER-001", "COM-WRITE-001", "CAR-INTERVIEW-001", "OSS-CONTRIB-001"],
  knowledgeDomains: ["APP", "PRAC", "RESP"],
  projects: [
    project("M10.P1", "Discovery & problem framing", "small", 10),
    project("M10.P2", "Capstone v0", "flagship", 50, true),
    project("M10.P3", "Capstone case study", "small", 10),
    project("M10.P4", "Specialisation deep-dive", "flagship", 40),
    project("M10.P5", "Graduation defense", "small", 8),
  ],
  flagshipProjectId: "M10.P2",
  gate: "The learner has publicly shipped an original AI product with a documented case study, delivered a specialisation deep-dive, and defended their work in a live review.",
  estimatedHours: { min: 100, max: 160 },
  modules: [
    mod({
      id: "M10.M1",
      order: 1,
      title: "Discovery and framing",
      purpose: "Choose a problem worth solving.",
      outcomes: ["Interview real users.", "Write a crisp problem statement."],
      advancesProject: "M10.P1",
      deliverable: "One-page problem framing signed off by a mentor or peer.",
      lessons: [
        lesson({
          id: "M10.M1.L1",
          title: "Find a real user",
          bigIdea: "A capstone without a user is a portfolio piece; with one, it's a product.",
          whyItMatters: "Real users produce real feedback.",
          objectives: ["Recruit a user.", "Run a 30-minute problem interview."],
          keyConcepts: ["problem interview", "job-to-be-done"],
          practice: "Draft five open-ended interview questions.",
          buildStep: "Interview one real user for the capstone.",
          aiConnection: "AI products succeed on problem fit, not model choice.",
          competencyIds: ["PROD-USER-001", "COM-WRITE-001"],
          knowledgeDomains: ["PRAC"],
          minutes: 60,
        }),
        lesson({
          id: "M10.M1.L2",
          title: "Framing and success metrics",
          bigIdea: "A framing document names the user, the pain, and how you will know you helped.",
          whyItMatters: "This is the north star for the next 50 hours of work.",
          objectives: ["Author a framing document.", "Choose two success metrics."],
          prerequisites: ["M10.M1.L1"],
          keyConcepts: ["problem statement", "success metric", "non-goals"],
          practice: "Redline three real framing documents.",
          buildStep: "Freeze the capstone framing.",
          aiConnection: "The framing dictates every downstream architecture choice.",
          competencyIds: ["PROD-USER-001"],
          knowledgeDomains: ["PRAC"],
          minutes: 60,
        }),
      ],
    }),
    mod({
      id: "M10.M2",
      order: 2,
      title: "Building the capstone",
      purpose: "Ship the original product.",
      outcomes: ["Deliver a running product to a real user.", "Iterate on user feedback at least twice."],
      prerequisites: ["M10.M1"],
      advancesProject: "M10.P2",
      deliverable: "Deployed capstone v0 with feedback log.",
      lessons: [
        lesson({
          id: "M10.M2.L1",
          title: "Scope like a professional",
          bigIdea: "The v0 does the smallest useful thing well.",
          whyItMatters: "Sprawling scope kills capstones.",
          objectives: ["Draft an aggressive v0 scope.", "Cut two features you love."],
          keyConcepts: ["MVP", "scope discipline"],
          practice: "Cut a bloated scope in half without losing the point.",
          buildStep: "Ship capstone v0.",
          aiConnection: "This is exactly how AI features ship inside real companies.",
          competencyIds: ["PROD-USER-001"],
          knowledgeDomains: ["PRAC"],
          minutes: 60,
        }),
        lesson({
          id: "M10.M2.L2",
          title: "Iterating with real users",
          bigIdea: "Real users beat imagined users; feedback loops beat plans.",
          whyItMatters: "This habit sustains careers.",
          objectives: ["Run a feedback session.", "Ship two prioritized improvements."],
          prerequisites: ["M10.M2.L1"],
          keyConcepts: ["feedback session", "prioritization", "changelog"],
          practice: "Convert five feedback quotes into three concrete tasks.",
          buildStep: "Ship capstone v0.1.",
          aiConnection: "AI feature success is measured post-launch, not pre.",
          competencyIds: ["PROD-USER-001", "COM-WRITE-001"],
          knowledgeDomains: ["PRAC"],
          minutes: 60,
        }),
      ],
    }),
    mod({
      id: "M10.M3",
      order: 3,
      title: "Specialisation deep-dive",
      purpose: "Go deep in one area that matches the learner's goals.",
      outcomes: ["Choose a specialisation.", "Ship a deep artifact within it."],
      prerequisites: ["M10.M2"],
      advancesProject: "M10.P4",
      deliverable: "A specialisation project with a public write-up.",
      lessons: [
        lesson({
          id: "M10.M3.L1",
          title: "Choosing a specialisation",
          bigIdea: "Depth in one area beats shallow in many at hiring time.",
          whyItMatters: "This choice shapes the next year.",
          objectives: ["Compare three candidate specialisations.", "Commit to one."],
          keyConcepts: ["specialisation", "T-shaped skill"],
          practice: "Write a paragraph for each candidate on 'what I'd ship first'.",
          buildStep: "Pick the specialisation.",
          aiConnection: "The industry rewards deep, transferable expertise.",
          competencyIds: ["CAR-INTERVIEW-001"],
          knowledgeDomains: ["PRAC"],
          minutes: 45,
        }),
        lesson({
          id: "M10.M3.L2",
          title: "Deep-dive project",
          bigIdea: "One serious artifact in your specialisation is worth ten tutorials.",
          whyItMatters: "This is often the piece that lands the first role.",
          objectives: ["Scope and ship a deep-dive artifact.", "Publish it publicly."],
          prerequisites: ["M10.M3.L1"],
          keyConcepts: ["depth artifact", "public write-up"],
          practice: "Draft the artifact's README before writing code.",
          buildStep: "Ship the deep-dive artifact.",
          aiConnection: "This is your entry ticket to the community you want to join.",
          competencyIds: ["OSS-CONTRIB-001", "COM-WRITE-001"],
          knowledgeDomains: ["PRAC"],
          minutes: 90,
        }),
      ],
    }),
    mod({
      id: "M10.M4",
      order: 4,
      title: "Career launch",
      purpose: "Turn the portfolio into interviews and offers.",
      outcomes: ["Defend the capstone in a live review.", "Run a job search with discipline."],
      prerequisites: ["M10.M3"],
      advancesProject: "M10.P5",
      deliverable: "Recorded graduation defense and a running job-search kanban.",
      lessons: [
        lesson({
          id: "M10.M4.L1",
          title: "Case studies and system stories",
          bigIdea: "Interviewers hire the story of a shipped project, not the code alone.",
          whyItMatters: "How you talk about your work matters as much as the work.",
          objectives: ["Write a capstone case study.", "Prepare a 20-minute walkthrough."],
          keyConcepts: ["case study", "system story", "trade-offs"],
          practice: "Rehearse the walkthrough once and self-critique.",
          buildStep: "Publish the case study.",
          aiConnection: "This is the AI-engineering interview format at real companies.",
          competencyIds: ["CAR-INTERVIEW-001", "COM-WRITE-001"],
          knowledgeDomains: ["PRAC"],
          minutes: 75,
        }),
        lesson({
          id: "M10.M4.L2",
          title: "Graduation defense",
          bigIdea: "You are now an AI engineer; defend it in public.",
          whyItMatters: "The defense is the ritual that closes the curriculum.",
          objectives: ["Present and defend the capstone.", "Answer three unrehearsed questions."],
          prerequisites: ["M10.M4.L1"],
          keyConcepts: ["defense", "Q&A", "next-step plan"],
          practice: "Have a peer stress-test the story.",
          buildStep: "Deliver the graduation defense.",
          aiConnection: "You now graduate into the community you spent this journey preparing for.",
          competencyIds: ["CAR-INTERVIEW-001"],
          knowledgeDomains: ["PRAC"],
          minutes: 90,
        }),
      ],
    }),
  ],
});
